### PR TITLE
zc - add announcements button on commons list page

### PR DESCRIPTION
**Pull request by imnotmomo**
## Overview
In this PR, a button (announcements) that navigate to /admin/announcements/commons.id was created, relevant tests are also added. Current  /admin/announcements/commons.id are navigated to the 404 Not Found page and waiting to be implemented.

## Screenshots
WeChat2dc0d1dd5cb7aca9902fea783dc64187

## Future Possibilities
will work on the next items in issue F2

## Validation
1. go to https://happycows-chendashi-dev.dokku-07.cs.ucsb.edu
2. Under Admin, choose List Commons
3. There is a button called Announcements
4. Click the button and will lead you to the not found page

## Tests
- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues
Not finished, but related to issue #4

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
We generally don't merge code into main if it leads to a 404.

Please implement, at least, a "placeholder page" (similar to those described in team03).

**Review by nadavital — DISMISSED** [review]
LGTM

**Review by YixinXue — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
Points reverted because feature was removed in PR #49

**Pull request merged**
