### PR TITLE
rk - homepage UI cleanup and "leave" button

### PR DESCRIPTION
**Pull request by rkibel**
## Overview
In this PR, I implemented a few things to increase visibility for the homepage. This continues off of issue #5:
- lightened CommonsCard colors so it is easier to look at (pastels instead of strong colors)
- added padding so elements are better spaced (title, common's name, flex for visit/join buttons)
- increased opacity + border for Join/Visit buttons for better visibility
- edited title to include a comma (ie "Howdy, Farmer Philip!)
- since I worked on issue #9 for users leaving a commons, I thought it would be fitting to include a "leave" button as well for leaving a commons. This button produces a window.alert onClick (no backend integration) and tests in CommonCard.test look for this window.alert upon clicking. In addition to serving as a placeholder for future revisions for backend, the purpose of adding this button is mainly to give the frontend a more complete look (with styling).

dokku deployment: https://happycows-rkibel-dev.dokku-07.cs.ucsb.edu

## Screenshots (Optional)
localhost
dokku

## Tests

- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Continues #5 
Continues #9

### CODE REVIEW

**Review by imnotmomo — DISMISSED** [review]
lgtm!

**Review by nadavital — DISMISSED** [review]
LGTM

**Review by sangitakunapuli — DISMISSED** [review]
UI looks awesome! I saw that you added the 'Leave' button for completeness of the page but we've since pivoted away from users being able to Leave a commons (https://ucsb-cs156-s24.slack.com/archives/C073GT1NXUM/p1716580120753429)

Please remove this button and then this PR is ready to merge!

**Comment by rkibel** [comment]
just pushed changes and removed the leave button, here is the new homepage on localhost:

image

**Review by nadavital — APPROVED** [review]
LGTM אין עליך אמאלהההההההההההה

**Review by AnikaArora — CHANGES_REQUESTED** [review]
Would you be able to shift the buttons to the right? For example, "visit" would be where "leave" was and "join" is shifted more to the right. I think it'll look slightly better that way.

**Comment by rkibel** [comment]
> Would you be able to shift the buttons to the right? For example, "visit" would be where "leave" was and "join" is shifted more to the right. I think it'll look slightly better that way.

This is slightly challenging to implement, for one there is a specified margin and padding through the className that cannot be overridden, so the button, by being in the flex, is as far to the right as possible. A workaround is to add a "ghost button" that is invisible and will take up space, but this is kind of ugly. 
This is the orientation the button had before the PR, any suggestions for how to proceed?

**Review by AnikaArora — APPROVED** [review]
LGTM!

**Pull request merged**
