### PR TITLE
na - started refactor of homepage

### PR DESCRIPTION
**Pull request by nadavital**
## Overview
In this PR, I started the refactoring of the homepage by making the old components more visually appealing by changing the title, as well as the background of the boxes. In addition, I set the stage for more future refactoring by creating new styles in the homepage css file, and adding more divs in the homepage which more clearly divide up the content.

dokku deployment: https://happycows-nadavital-dev.dokku-07.cs.ucsb.edu

started issue #5 

## Screenshots (Optional)
Screenshot 2024-05-21 at 6 10 25 PM

## Feedback Request (Optional)
Please give suggestions on the following:
- What other refactoring would you like to see on the homepage?

## Future Possibilities (Optional)

Some possible points could be:
- Change the items in the list to be cards which makes them more visually appealing, approachable, and could enable future functionality such as drag and drops or pop up menus from clicking on them
- limit the length of the name field of the common to be one line

## Validation (Optional)
1. Download this branch.
2. Run the project.
3. Go to the homepage
4. see that everything looks as it should

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`)

### CODE REVIEW

**Review by mczimmermann — APPROVED** [review]
Everything looks good to me!

**Review by rkibel — APPROVED** [review]
Changes look good to me

**Review by AnikaArora — CHANGES_REQUESTED** [review]
Please provide the link to your dokku deployment for this branch so we can test it. Also, in the PR description, it currently says closes issue #__; I think it would be better to say works on issue #__ instead of 'closes' because there are still other objectives in that issue that can be addressed. 
EDIT: sorry, I just saw the link to the dokku deployment. I'm taking a look at that, but in the meanwhile please fix the PR description.

**Review by AnikaArora — APPROVED** [review]
LGTM!

**Pull request merged**
