### PR TITLE
jf - jobs pagination on admin jobs page

### LINKED ISSUE #38: FEATURE: Update Jobs display native Pagination implemented in OurTable
## User Story
- As an admin
- I can see both the most recent jobs performed and all jobs that have been executed in the history
- So that I can better understand what's happening in the game

## Discussion

The buttons in PagedJobsTable were a quick attempt at building an MVP, but since then,
we've discovered that React Bootstrap has components just for this purpose: see https://react-bootstrap.netlify.app/docs/components/pagination. This feature has already been implemented to display profits in `ProfitsTable.js` using `OurTable.js.` in #10, so it only stands to reason that we should do this for Jobs too.

## Acceptance Criteria

- [x] The admin page uses the React Bootstrap component for pagination instead of its current implementation without losing functionality
- [x] It is easy for the user to navigate through their profits, and the user interface looks clean.

### PR DESCRIPTION
**Pull request by jamesyfu**
## Overview

In this PR, we implemented jobs pagination using the react-bootstrap component that is implemented in OurTable.js on the admin jobs page. This would bring it up to standard with the current table format already implemented on the profits display on the play page.

Please note the hard dependency this PR has on the bugfix implemented in #40, which has not yet been merged at the time of creating this PR. Please merge PR #40 before merging this PR. Currently deployed on: https://proj-happycows-james-y-f-dev.dokku-07.cs.ucsb.edu/admin/jobs

## Screenshots

Before:

Screenshot 2024-05-27 at 11 25 25 PM

After:

Screenshot 2024-05-28 at 5 49 03 PM

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues
Closes #38

### CODE REVIEW

**Review by mczimmermann — DISMISSED** [review]
LGTM!

**Review by pconrad — DISMISSED** [review]
Can you remove the updates to package-lock.json?  See:
https://ucsb-cs156.github.io/topics/pull_requests/package_lock_json.html

After that it should be mergeable.  I've looked at the code and tested it on Dokku.

**Comment by jamesyfu** [comment]
I have reverted the changes to package-lock.json, should be mergeable now!

**Review by imnotmomo — DISMISSED** [review]
lgtm!

**Review by AnikaArora — DISMISSED** [review]
LGTM!

**Review by AnikaArora — APPROVED** [review]

**Review by mczimmermann — APPROVED** [review]
LGTM!

**Review by AnikaArora — DISMISSED** [review]
LGTM!

**Review by mczimmermann — DISMISSED** [review]
LGTM!

**Review by Aasish-Virjala — DISMISSED** [review]
LGTM

**Review by AnikaArora — DISMISSED** [review]

**Review by Aasish-Virjala — DISMISSED** [review]
LGTM

**Review by AnikaArora — APPROVED** [review]

**Review by AnikaArora — DISMISSED** [review]
lgtm

**Review by pconrad — APPROVED** [review]
LGTM

**Review by AnikaArora — APPROVED** [review]
lgtm

**Pull request merged**
